convert type of camids (imgid) from string to int
Seem that pytorch does not convert list of string to Tensor auto, which will causing error  "AttributeError: 'list' object has no attribute 'to'" when testing.